# Generated by Django 4.0.5 on 2022-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_wallet_balance_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=100),
        ),
    ]
