# Generated by Django 4.0.5 on 2022-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_wallet_balance_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
