# Generated by Django 4.0.5 on 2022-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_alter_transaction_commision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commision",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        ),
    ]
