# Generated by Django 4.0.5 on 2022-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_alter_transaction_commision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commision",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
