# Generated by Django 4.0.5 on 2022-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_alter_transaction_commision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commision",
            field=models.IntegerField(),
        ),
    ]
