# Generated by Django 4.0.5 on 2022-10-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_alter_transaction_commision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="transer_amount",
            new_name="transfer_amount",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="PAID", max_length=100),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="type",
            field=models.CharField(
                choices=[("visa", "Visa"), ("mastercard", "Mastercard")], max_length=25
            ),
        ),
    ]
